version: '2'
services:
  mongo:
    image: mongo
    command: ["--storageEngine", "wiredTiger"]
  server:
    image: node
    volumes:
      - .:/app
    ports:
      - 9000:8080
    depends_on:
      - mongo
    working_dir: /app
    entrypoint: ./config/server/entrypoint.sh
